CREATE TABLE meals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE,
  meal_type VARCHAR(20),
  food VARCHAR(100)
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);